version: '3'

services: 
    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: graphqldb
            MYSQL_USER: api
            MYSQL_PASSWORD: password
        ports: 
            - 3306:3306
        volumes: 
            - mysql_graphql_data:/var/lib/mysql

volumes:
    mysql_graphql_data:
        name: mysql_graphql_data
